name: Run tests after Vercel deployment

on:
  deployment:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: |
          echo "Deployment URL: ${{ github.event.deployment.payload.url }}"
          echo "Commit SHA: ${{ github.event.deployment.payload.sha }}"
          npm test
